### ISSUE TITLE
Not working on Samsung Galaxy Tab A SM-T597V

### ISSUE THREAD

**Issue by jack5432109** [mcdz/LocalIP#1]
I cloned the repo, built the apk using Android studio and installed it with `adb install`, I don't see that tile. What am i missing?

**Comment by mcdz** [comment]
There can be 2 reasons,
1. Your device doesn't supports additional tiles.
2. You Haven't tried to look into add tile section. The tile won't be automatically added to notification panel, you need to add it manually.

Btw, the app is released on Play Store. Just in case, https://play.google.com/store/apps/details?id=com.mcdz.seeip

Please share updates if issue is resolved,

**Comment by jack5432109** [comment]
- I wasn't able to find a way to add tiles for the samsung galaxy tab. But when I open the page for the app from play store, it does say that _This app may not be optimized for your device_.
- I installed it on another phone of mine, it took a long time for it to fetch public IP, and I wasn't sure whether it will do that, but it did eventually

**Comment by mcdz** [comment]
Yes, fetching public ip is based on network connection. Maybe some network issues. it usually take 1-3 seconds to fetch it. based on network conditions, it'll vary.
